version: '3'

services:

    fastapi:
        build: .
        env_file:
            - ./.env
        restart: always
        container_name: asmi_backend
        ports:
          - 9999:8000
        image: say_my_name/asmi_backend